/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Audioplayer: typeof import('./src/components/blocks/audioplayer.vue')['default']
    ButtonNav: typeof import('./src/components/ButtonNav.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconMynauiStopOctagon: typeof import('~icons/mynaui/stop-octagon')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IPhSignOutFill: typeof import('~icons/ph/sign-out-fill')['default']
    IPrimeSignOut: typeof import('~icons/prime/sign-out')['default']
    Reactive: typeof import('./src/components/blocks/reactive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrainScene: typeof import('./src/components/TrainScene.vue')['default']
  }
}
