/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Audioplayer: typeof import('./components/blocks/audioplayer.vue')['default']
    BlockRenderer: typeof import('./components/BlockRenderer.vue')['default']
    ButtonNav: typeof import('./components/ButtonNav.vue')['default']
    ContinueLater: typeof import('./components/ContinueLater.vue')['default']
    Reactive: typeof import('./components/blocks/reactive.vue')['default']
    ReactiveBtn: typeof import('./components/blocks/reactiveBtn.vue')['default']
    ReactiveMessage: typeof import('./components/blocks/reactiveMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimerClock: typeof import('./components/TimerClock.vue')['default']
    TrainScene: typeof import('./components/TrainScene.vue')['default']
  }
}
